### ISSUE TITLE
Super impose ligands issue with oxazole,thiazole, and imidazole 

### ISSUE THREAD

**Issue by Oulfin** [UCL-CCS/TIES#323]
Hi again,

I just realized that when one wants to perform a transformation from oxazole, thiazole, or imidazole to just add a methyl, it crashes. However, when the same transformation is done using isoxazole, isothiazole, and pyrazole to a methyl, it works.

Do you know what is the possible issue?

Best,

![Fail_superimpose](https://github.com/UCL-CCS/TIES/assets/89843064/957dc82f-b4af-4ef5-9005-710dece8945a)

**Comment by bieniekmateusz** [comment]
Hi @Oulfin, I'll have some time later this week and will get back to you on this. Thanks

**Comment by Oulfin** [comment]
Hi @bieniekmateusz,

I found the error. In the "pair.py"

Line 391:
if "Could not find bond parameter for:" in line:  --> if "Could not find bond parameter for" in line:

Line 394:
elif "Could not find angle parameter for:" in line:  --> elif "Could not find angle parameter for" in line: 

The problem was that it was not able to detect angle parameter from the leap.log and create the dummy angles parameter.

Thanks!

**Comment by bieniekmateusz** [comment]
Hi @Oulfin , apologies for the delay. I will look into this this weekend. This error occasionally showed up when the "antechamber" was too old or too new: because they changed the wording (See #319). 

Would you be able to provide your files for the superimposition? I'll check the different options (like utilising the coordinates) etc. Thanks!

**Comment by Oulfin** [comment]
Hi,

Sorry for the late response, I was away. So far I could make it word by changing the wording. I did not get error after that.

Thanks!
